### ISSUE TITLE
can't find ros_controller

### ISSUE THREAD

**Issue by Abduoit** [husky/husky_manipulation#12]
Hi

I am using Melodic Branch on ROS Kinetic, running on a Husky robot with UR5. I expect to see the ROS_Controller like in this  [file](https://github.com/husky/husky_manipulation/blob/melodic-devel/husky_ur_bringup/config/ur_controllers.yaml). But I can't see the controllers, I only see `husky_velocity_controller`, as seen below.
```
administrator@administrator:~$ rosservice call /controller_manager/list_controllers
controller: 
  - 
    name: "husky_joint_publisher"
    state: "running"
    type: "joint_state_controller/JointStateController"
    claimed_resources: 
      - 
        hardware_interface: "hardware_interface::JointStateInterface"
        resources: []
  - 
    name: "husky_velocity_controller"
    state: "running"
    type: "diff_drive_controller/DiffDriveController"
    claimed_resources: 
      - 
        hardware_interface: "hardware_interface::VelocityJointInterface"
        resources: [front_left_wheel, front_right_wheel, rear_left_wheel, rear_right_wheel]
```
When I use `rosrun rqt_joint_trajectory_controller rqt_joint_trajectory_controller` I find under the `ur_controller_list` the `ur_arm_scaled_pos_joint_traj_controller`.

The purpose of that, I need to switch to `velocity_controller`, so I can send velocity commands to the arm and to the Husky. 

Any help please ?

**Comment by dniewinski** [comment]
What comes up when you run `rosservice call /ur/controller_manager/list_controllers`?

**Comment by Abduoit** [comment]
I got this 
```
administrator@administrator:~$ rosservice call /ur/controller_manager/list_controllers
controller: 
  - 
    name: "ur_arm_joint_state_controller"
    state: "running"
    type: "joint_state_controller/JointStateController"
    claimed_resources: 
      - 
        hardware_interface: "hardware_interface::JointStateInterface"
        resources: []
  - 
    name: "ur_arm_pos_joint_traj_controller"
    state: "stopped"
    type: "position_controllers/JointTrajectoryController"
    claimed_resources: 
      - 
        hardware_interface: "hardware_interface::PositionJointInterface"
        resources: [ur_arm_elbow_joint, ur_arm_shoulder_lift_joint, ur_arm_shoulder_pan_joint, ur_arm_wrist_1_joint,
  ur_arm_wrist_2_joint, ur_arm_wrist_3_joint]
  - 
    name: "ur_arm_scaled_pos_joint_traj_controller"
    state: "running"
    type: "position_controllers/ScaledJointTrajectoryController"
    claimed_resources: 
      - 
        hardware_interface: "ur_controllers::ScaledPositionJointInterface"
        resources: [ur_arm_elbow_joint, ur_arm_shoulder_lift_joint, ur_arm_shoulder_pan_joint, ur_arm_wrist_1_joint,
  ur_arm_wrist_2_joint, ur_arm_wrist_3_joint]
  - 
    name: "ur_arm_speed_scaling_state_controller"
    state: "running"
    type: "ur_controllers/SpeedScalingStateController"
    claimed_resources: 
      - 
        hardware_interface: "ur_controllers::SpeedScalingInterface"
        resources: []
  - 
    name: "ur_arm_force_torque_sensor_controller"
    state: "running"
    type: "force_torque_sensor_controller/ForceTorqueSensorController"
    claimed_resources: 
      - 
        hardware_interface: "hardware_interface::ForceTorqueSensorInterface"
        resources: []
  - 
    name: "ur_arm_robot_status_controller"
    state: "running"
    type: "industrial_robot_status_controller/IndustrialRobotStatusController"
    claimed_resources: 
      - 
        hardware_interface: "industrial_robot_status_interface::IndustrialRobotStatusInterface"
        resources: []
```

All position control, there's no velocity, and I am looking to use [joint_group_vel_controller](https://github.com/husky/husky_manipulation/blob/melodic-devel/husky_ur_bringup/config/ur_controllers.yaml#L129) but I can't find it.
